// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, SpinBox } from "std-widgets.slint";
import { Page } from "page.slint";

export ControlsPage := Page {
    title: "Controls";
    description: "This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".";

    GroupBox {
        vertical-stretch: 0;
        title: "Buttons";

        HorizontalLayout {
            spacing: 8px;
            alignment: start;

            Button {
                text: "Regular Button";
            }

            Button {
                text: "Regular Button";
                icon: @image-url("../../thumbsup.png");
            }

            Button {
                checkable: true;
                text: checked ? "ON" : "OFF";
            }
        }
    }

    GroupBox {
        title: "CheckBox - SpinBox - ComboBox";
        vertical-stretch: 0;

        HorizontalBox {
            checkbox := CheckBox {
                text: checkbox.checked ? "(checked)" : "(unchecked)";
                checked: true;
            }


        SpinBox {
            vertical-stretch: 0;
            value: 42;
        }

            ComboBox {
                model: ["Select Something", "From this", "Combobox"];
            }
        }


    }

    GroupBox {
        title: "LineEdit";
        vertical-stretch: 0;

        LineEdit {
            placeholder-text: "Enter some text";
        }
    }

    GroupBox {
        title: "Slider";
        vertical-stretch: 0;

        Slider {
            min-width: 160px;
            minimum: -100;
            maximum: 100;
            value: 42;
        }
    }

    GroupBox {
        title: "TabWidget";

        TabWidget {
            Tab {
                title: "Tab 1";

                VerticalBox {
                    alignment: start;

                    GroupBox {
                        title: "Content of tab 1";

                        VerticalBox {
                            alignment: start;

                            Button {
                                text: "Click me";
                            }
                        }
                    }
                }
            }

            Tab {
                title: "Tab 2";

                VerticalBox {
                    alignment: start;

                    GroupBox {
                        title: "Content of tab 2";

                        VerticalBox {
                            alignment: start;

                            CheckBox {
                                text: "Check me";
                            }
                        }
                    }
                }
            }

            Tab {
                title: "Tab 3";

                VerticalBox {
                    Text {
                        text: "Content of tab 3";
                    }
                }
            }
        }
    }
}
