import { Button, GroupBox, ComboBox, CheckBox, LineEdit, HorizontalBox  } from "std-widgets.slint";
import { Page } from "page.slint";


export global InstallArgs := {
    property <string> xtensa-rust-version;
    property <string> export-file;
    property <string> default-host;
    property <string> log-level: "info";
    property <string> esp-idf-version: "none";
    property <string> nightly-version: "nightly";
    property <bool> profile-minimal: true;
    // Targets
    property <bool> esp32-value: true;
    property <bool> esp32s2-value: true;
    property <bool> esp32s3-value: true;
    property <bool> esp32c2-value: true;
    property <bool> esp32c3-value: true;
    // Crates
    property <bool> espflash-value;
    property <bool> cargo-espflash-value;
    property <bool> ldproxy-value;
    property <bool> sccache-value;


    callback install();
}


export InstallPage := Page {
    title: "Install";
    description: "Install the required toolchains for developing applications in Rust for Espressif SoC's.";

    GroupBox {
        title: "Targets:";
        vertical-stretch: 0;

        HorizontalBox {
            esp32 := CheckBox {
                text: "ESP32";
                checked <=> InstallArgs.esp32-value;
            }

            esp32s2 := CheckBox {
                text: "ESP32-S2";
                checked <=> InstallArgs.esp32s2-value;
            }

            esp32s3 := CheckBox {
                text: "ESP32-S3";
                checked <=> InstallArgs.esp32s3-value;
            }

            esp32c2 := CheckBox {
                text: "ESP32-C2";
                checked <=> InstallArgs.esp32c2-value;
            }

            esp32c3 := CheckBox {
                text: "ESP32-C3";
                checked <=> InstallArgs.esp32c3-value;
            }
        }

    }

    GroupBox {
        title: "Extra Crates:";
        vertical-stretch: 0;

        HorizontalBox {
            espflash := CheckBox {
                text: "espflash";
                checked <=> InstallArgs.espflash-value;
            }

            cargo-espflash := CheckBox {
                text: "cargo-espflash";
                checked <=> InstallArgs.cargo-espflash-value;
            }

            ldproxy := CheckBox {
                text: "ldproxy";
                checked <=>  InstallArgs.ldproxy-value;
            }

            sccache := CheckBox {
                text: "sccache";
                checked <=> InstallArgs.sccache-value;
            }
        }

    }

    GroupBox {
        title: "Xtensa Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text <=> InstallArgs.xtensa-rust-version;
        }
    }

    GroupBox {
        title: "Nightly Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text <=> InstallArgs.nightly-version;
        }
    }

    GroupBox {
        title: "Export file";
        vertical-stretch: 0;

        LineEdit {
            text <=> InstallArgs.export-file;
        }
    }

    GroupBox {
        title: "Default Host";
        vertical-stretch: 0;
        ComboBox {
            current-value <=> InstallArgs.default-host;
            model: [ "x86_64-unknown-linux", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin","x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu",];
        }
    }

    // GroupBox {
    //     title: "LLVM Version";
    //     vertical-stretch: 0;

    //      ComboBox {
    //         model: ["15"];
    //     }
    // }

    GroupBox {
        title: "Log Level";
        vertical-stretch: 0;
        ComboBox {
            current-value <=> InstallArgs.log-level;
            model: ["debug", "info", "warn", "error"];
        }
    }

    GroupBox {
        title: "ESP-IDF Version";
        vertical-stretch: 0;

         ComboBox {
            current-value <=> InstallArgs.esp-idf-version;
            model: [ "none", "release/v4.4", "release/v5.0", "master", "v4.4.1", "v4.4.2", "v4.4.3"];
            selected(version) => {
                if (version != "none") {
                    InstallArgs.ldproxy-value = true;
                } else {
                    InstallArgs.ldproxy-value = false;
                }
             }
        }
    }

    GroupBox {

        minimal := CheckBox {
            text: "Minify Installation?";
            checked <=> InstallArgs.profile-minimal;
        }

        Button {
            text: "Install";
            clicked => {
                InstallArgs.install();
            }
        }

    }
}
