// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox, ComboBox, CheckBox, LineEdit, HorizontalBox  } from "std-widgets.slint";
import { Page } from "page.slint";


export global Espup := {
    property <string> xtensa-rust-version;
    property <string> export-file;
    property <string> default-host;
    property <bool> esp32;

    callback install();
    callback esp32();
}


export InstallPage := Page {
    title: "Install";
    description: "Install the required toolchains for developing applications in Rust for Espressif SoC's.";

    GroupBox {
        title: "Targets:";
        vertical-stretch: 0;

        HorizontalBox {
            esp32 := CheckBox {
                text: "ESP32";
                checked: false;
                toggled => {
                    Espup.esp32();
                }
            }

            esp32s2 := CheckBox {
                text: "ESP32-S2";
                checked: false;
            }

            esp32s3 := CheckBox {
                text: "ESP32-S3";
                checked: false;
            }

            esp32c2 := CheckBox {
                text: "ESP32-C2";
                checked: false;
            }

            esp32c3 := CheckBox {
                text: "ESP32-C3";
                checked: false;
            }
        }

    }

    GroupBox {
        title: "Extra Crates:";
        vertical-stretch: 0;

        HorizontalBox {
            espflash := CheckBox {
                text: "espflash";
                checked: false;
            }

            cargo-espflash := CheckBox {
                text: "cargo-espflash";
                checked: false;
            }

            ldproxy := CheckBox {
                text: "ldproxy";
                checked: false;
                // CHECK IF ESP-IDF
            }

            sccache := CheckBox {
                text: "sccache";
                checked: false;
            }
        }

    }

    GroupBox {
        title: "Xtensa Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text: Espup.xtensa-rust-version;
        }
    }

    GroupBox {
        title: "Nightly Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text: "nightly";
        }
    }

    GroupBox {
        title: "Export file";
        vertical-stretch: 0;

        LineEdit {
            text: "export-esp.ps1";
        }
    }

    GroupBox {
        title: "Default Host";
        vertical-stretch: 0;

        ComboBox {
            model: [ "x86_64-unknown-linux", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin","x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu",];
        }
    }

    // GroupBox {
    //     title: "LLVM Version";
    //     vertical-stretch: 0;

    //      ComboBox {
    //         model: ["15"];
    //     }
    // }

    GroupBox {
        title: "Log Level";
        vertical-stretch: 0;
        ComboBox {
            current-value: "info";
            model: ["debug", "info", "warn", "error"];
        }
    }

    GroupBox {
        title: "ESP-IDF Version";
        vertical-stretch: 0;

         ComboBox {
            current-value: "none";
            model: [ "none", "release/v4.4", "release/v5.0", "master", "v4.4.1", "v4.4.2", "v4.4.3"];
        }
    }

    GroupBox {
        Button {
            text: "Install";
            clicked => {
                Espup.install();
            }
        }

    }
}
