// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, SpinBox } from "std-widgets.slint";
import { Page } from "page.slint";


export InstallPage := Page {
   title: "Install";
    description: "This page gives an overview of the default widget set provided by Slint. The widgets are available in different styles native, fluent-(dark/light) and material-(dark/light). The widgets can be imported from \"std-widgets.slint\".";

    GroupBox {
        title: "Targets:";
        vertical-stretch: 0;

        HorizontalBox {
            esp32 := CheckBox {
                text: "ESP32";
                checked: false;
            }

            esp32s2 := CheckBox {
                text: "ESP32-S2";
                checked: false;
            }

            esp32s3 := CheckBox {
                text: "ESP32-S3";
                checked: false;
            }

            esp32c2 := CheckBox {
                text: "ESP32-C2";
                checked: false;
            }

            esp32c3 := CheckBox {
                text: "ESP32-C3";
                checked: false;
            }
        }

    }

    GroupBox {
        title: "Extra Crates:";
        vertical-stretch: 0;

        HorizontalBox {
            espflash := CheckBox {
                text: "espflash";
                checked: false;
            }

            cargo-espflash := CheckBox {
                text: "cargo-espflash";
                checked: false;
            }

            ldproxy := CheckBox {
                text: "ldproxy";
                checked: false;
                // CHECK IF ESP-IDF
            }

            sccache := CheckBox {
                text: "sccache";
                checked: false;
            }
        }

    }

    GroupBox {
        title: "Xtensa Rust Version";
        vertical-stretch: 0;

        LineEdit {
            placeholder-text: "1.65.0.1";
        }
    }

    GroupBox {
        title: "Nightly Rust Version";
        vertical-stretch: 0;

        LineEdit {
            placeholder-text: "nightly";
        }
    }

    GroupBox {
        title: "Export file";
        vertical-stretch: 0;

        LineEdit {
            placeholder-text: "export-esp.ps1";
        }
    }

    GroupBox {
        title: "Default Host";
        vertical-stretch: 0;

         ComboBox {
            model: ["x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu", "x86_64-unknown-linux"];
        }
    }

    GroupBox {
        title: "LLVM Version";
        vertical-stretch: 0;

         ComboBox {
            model: ["15"];
        }
    }

    GroupBox {
        title: "Log Level";
        vertical-stretch: 0;
        ComboBox {
            current-value: "info";
            model: ["debug", "info", "warn", "error"];
        }
    }

    GroupBox {
        title: "ESP-IDF Version";
        vertical-stretch: 0;

         ComboBox {
            model: [ "none", "release/v4.4", "release/v5.0", "master", "v4.4.1", "v4.4.2", "v4.4.3"];
        }
    }




    GroupBox {
        Button {
            text: "Install";
            // Add callback
        }

    }
}
