// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox } from "std-widgets.slint";
import { Page } from "page.slint";

export UninstallPage := Page {
    title: "Uninstall";
    description: "Allows to uninstall the toolchains required for developing applications in Rust for Espressif SoC's.";
    callback uninstall();
    GroupBox {
        Button {
            text: "Uninstall";
            clicked => {
                uninstall();
            }
        }
    }
}
