// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Button, GroupBox, ComboBox, LineEdit } from "std-widgets.slint";
import { Page } from "page.slint";


export global UpdateArgs := {
    property <string> xtensa-rust-version;
    property <string> log-level: "info";


    callback update();
}

export UpdatePage := Page {
    title: "Update";
    description: "Allows to update the  required toolchains for developing applications in Rust for Espressif SoC's.";

    GroupBox {
        title: "Xtensa Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text <=> UpdateArgs.xtensa-rust-version;
        }
    }
    GroupBox {
        title: "Log Level";
        vertical-stretch: 0;
        ComboBox {
            current-value <=> UpdateArgs.log-level;
            model: ["debug", "info", "warn", "error"];
        }
    }

    GroupBox {
        Button {
            text: "Update";
            clicked => {
                UpdateArgs.update();
            }
        }
    }
}
