import { Button, GroupBox, ComboBox, LineEdit } from "std-widgets.slint";
import { Page } from "page.slint";


export global UpdateArgs := {
    property <string> xtensa-rust-version;
    property <string> log-level: "info";
    property <string> default-host;

    callback update();
}

export UpdatePage := Page {
    title: "Update";
    description: "Allows to update the  required toolchains for developing applications in Rust for Espressif SoC's.";

    GroupBox {
        title: "Xtensa Rust Version";
        vertical-stretch: 0;

        LineEdit {
            text <=> UpdateArgs.xtensa-rust-version;
        }
    }

    GroupBox {
        title: "Default Host";
        vertical-stretch: 0;
        ComboBox {
            current-value <=> UpdateArgs.default-host;
            model: [ "x86_64-unknown-linux", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin","x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu",];
        }
    }

    GroupBox {
        title: "Log Level";
        vertical-stretch: 0;
        ComboBox {
            current-value <=> UpdateArgs.log-level;
            model: ["debug", "info", "warn", "error"];
        }
    }

    GroupBox {
        Button {
            text: "Update";
            clicked => {
                UpdateArgs.update();
            }
        }
    }
}
