// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

// import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { InstallPage, UpdatePage, UninstallPage } from "ui/pages/pages.slint";
import { SideBar } from "ui/side_bar.slint";
import { Espup } from "ui/pages/install_page.slint";

export { Espup }

App := Window {
    preferred-width: 700px;
    preferred-height: 800px;
    title: "Espup";
    icon: @image-url("./esp-rs.png");

    property <string> espup-ui-version: "x.y.z";

    HorizontalLayout {
        side-bar := SideBar {
            title: "Espup  \{espup-ui-version}";
            model: [ "Install", "Update", "Uninstall" ];
        }

        if(side-bar.current-item == 0) : InstallPage {}
        if(side-bar.current-item == 1) : UpdatePage {}
        if(side-bar.current-item == 2) : UninstallPage {}
    }
}

