// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { InstallPage, ControlsPage, ListViewPage, TextEditPage } from "ui/pages/pages.slint";
import { SideBar } from "ui/side_bar.slint";

App := Window {
    preferred-width: 700px;
    preferred-height: 800px;
    title: "Espup";
    icon: @image-url("./esp-rs.png");

    property <string> espup-ui-version: "x.y.z";

    HorizontalLayout {
        side-bar := SideBar {
            title: "Espup  \{espup-ui-version}";
            model: [ "Install", "Controls", "ListView", "TextEdit"];
        }

        if(side-bar.current-item == 0) : InstallPage {}
        if(side-bar.current-item == 1) : ControlsPage {}
        if(side-bar.current-item == 2) : ListViewPage {}
        if(side-bar.current-item == 3) : TextEditPage {}
    }
}
