// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { InstallPage, ControlsPage, ListViewPage, TextEditPage } from "ui/pages/pages.slint";
import { GallerySettings } from "ui/gallery_settings.slint";
import { SideBar } from "ui/side_bar.slint";

App := Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: "Espup";
    icon: @image-url("../../logo/esp-rs.png");

    HorizontalLayout {
        side-bar := SideBar {
            title: "Espup";
            model: ["Controls", "ListView", "TextEdit", "Install"];
        }

        if(side-bar.current-item == 0) : ControlsPage {}
        if(side-bar.current-item == 1) : ListViewPage {}
        if(side-bar.current-item == 2) : TextEditPage {}
        if(side-bar.current-item == 3) : InstallPage {}
    }
}
